export{default as Blog } from './blog/Blog'
export{default as Features } from './features/Features'
export{default as Footer } from './footer/Footer'
export{default as Header } from './header/Header'
export{default as Possibilty } from './possibilty/Possiblity'
export{default as Whatgpt } from './whatgp3/Whatgpt'
